openapi: 3.0.1

info:
  title: Dish API
  version: 1.0.0
  description: Super cool dish API

servers:
  - url: 'https://{customDomain}/{basePath}'
    description: Custom server
    variables:
      customDomain:
        default: ''
      basePath:
        enum:
          - 'api/v1'
        default: 'api/v1'

paths:
  /api:
  /ping:
    $ref: 'Operation/Ping.yaml'
  /get-all-dishes-by-recipe:
    $ref: 'Operation/GetAllDishesByRecipe.yaml'